자동차 배기량에 따라 고속도로 연비가 다른지 알아 보려고 한다. displ(배기량)이 4 이하인
자동차와 5 이상인 자동차 중 어떤 자동차의 hwy (고속도로 연비) 평균이 더 높은지 알아봐라

In [51]:
import pandas as pd
import numpy as np
import csv

In [9]:
mpg = pd.read_csv("data/mpg.csv")
mpga = mpg.query("displ <= 4")
mpga["hwy"].mean()

np.float64(25.96319018404908)

In [11]:
mpg = pd.read_csv("data/mpg.csv")
mpgb = mpg.query("displ >= 5")
mpgb["hwy"].mean()
#평균도 구하기

np.float64(18.07894736842105)

In [18]:
mpg
mpg_audi = mpg.query('manufacturer == "audi"')
mpg_toyota = mpg.query('manufacturer == "toyota"')
mpg_audi["cty"].mean()

np.float64(17.61111111111111)

In [19]:
mpg_toyota["cty"].mean()

np.float64(18.529411764705884)

In [23]:
mpg_a = mpg.query('manufacturer in["chevrolet", "ford", "honda"]')
mpg_a["hwy"].mean()

np.float64(22.50943396226415)

In [24]:
mpg["cty"]

0      18
1      21
2      20
3      21
4      16
       ..
229    19
230    21
231    16
232    18
233    17
Name: cty, Length: 234, dtype: int64

In [30]:
exam = pd.read_csv("data/exam.csv")
exam[["nclass", "math", "english"]]
exam.query("math >= 90")

   id  nclass  math  english  science
7   8       2    90       78       25

In [31]:
exam[["math"]]

    math
0     50
1     60
2     45
3     30
4     25
5     50
6     80
7     90
8     20
9     50
10    65
11    45
12    46
13    48
14    75
15    58
16    65
17    80
18    89
19    78

In [33]:
exam_new = exam.copy()
exam_new

    id  nclass  math  english   science
0    1       1    50       98  10000000
1    2       1    60       97        60
2    3       1    45       86        78
3    4       1    30       98        58
4    5       2    25       80        65
5    6       2    50       89        98
6    7       2    80       90        45
7    8       2    90       78        25
8    9       3    20       98        15
9   10       3    50       98        45
10  11       3    65       65        65
11  12       3    45       85        32
12  13       4    46       98        65
13  14       4    48       87        12
14  15       4    75       56        78
15  16       4    58       98        65
16  17       5    65       68        98
17  18       5    80       78        90
18  19       5    89       68        87
19  20       5    78       83        58

In [35]:
exam_new.drop(columns = "math")

    id  nclass  english   science
0    1       1       98  10000000
1    2       1       97        60
2    3       1       86        78
3    4       1       98        58
4    5       2       80        65
5    6       2       89        98
6    7       2       90        45
7    8       2       78        25
8    9       3       98        15
9   10       3       98        45
10  11       3       65        65
11  12       3       85        32
12  13       4       98        65
13  14       4       87        12
14  15       4       56        78
15  16       4       98        65
16  17       5       68        98
17  18       5       78        90
18  19       5       68        87
19  20       5       83        58

In [36]:
exam_new.drop(columns = ["math", "english"])

    id  nclass   science
0    1       1  10000000
1    2       1        60
2    3       1        78
3    4       1        58
4    5       2        65
5    6       2        98
6    7       2        45
7    8       2        25
8    9       3        15
9   10       3        45
10  11       3        65
11  12       3        32
12  13       4        65
13  14       4        12
14  15       4        78
15  16       4        65
16  17       5        98
17  18       5        90
18  19       5        87
19  20       5        58

In [37]:
exam.query("math >= 50")[["id", "math"]]

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

In [38]:
exam.query("math >= 50")\
    [["id", "math"]]

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

In [40]:
mpg = pd.read_csv("data/mpg.csv")
mpg_new = mpg[["category", "cty"]]
mpg_new

    category  cty
0    compact   18
1    compact   21
2    compact   20
3    compact   21
4    compact   16
..       ...  ...
229  midsize   19
230  midsize   21
231  midsize   16
232  midsize   18
233  midsize   17

[234 rows x 2 columns]

In [42]:
mpg_suv = mpg.query('category == "suv"')
mpg_suv["cty"].mean()

np.float64(13.5)

In [43]:
mpg_compact = mpg.query('category == "compact"')
mpg_compact["cty"].mean()

np.float64(20.127659574468087)

In [ ]:
sort_values("math", ascending=False)

In [46]:
mpg_audi = mpg.query('manufacturer == "audi"')
mpg_audi.sort_values("hwy", ascending=False).head(5)

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
9,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact

In [ ]:
df.assign() #파생변수 추가하

In [48]:
exam.assign(total = exam["math"] + exam["english"])

    id  nclass  math  english   science  total
0    1       1    50       98  10000000    148
1    2       1    60       97        60    157
2    3       1    45       86        78    131
3    4       1    30       98        58    128
4    5       2    25       80        65    105
5    6       2    50       89        98    139
6    7       2    80       90        45    170
7    8       2    90       78        25    168
8    9       3    20       98        15    118
9   10       3    50       98        45    148
10  11       3    65       65        65    130
11  12       3    45       85        32    130
12  13       4    46       98        65    144
13  14       4    48       87        12    135
14  15       4    75       56        78    131
15  16       4    58       98        65    156
16  17       5    65       68        98    133
17  18       5    80       78        90    158
18  19       5    89       68        87    157
19  20       5    78       83        58    161

In [49]:
exam.assign(total = exam["math"] + exam["english"], mean = (exam["math"] + exam["english"])/2)

    id  nclass  math  english   science  total  mean
0    1       1    50       98  10000000    148  74.0
1    2       1    60       97        60    157  78.5
2    3       1    45       86        78    131  65.5
3    4       1    30       98        58    128  64.0
4    5       2    25       80        65    105  52.5
5    6       2    50       89        98    139  69.5
6    7       2    80       90        45    170  85.0
7    8       2    90       78        25    168  84.0
8    9       3    20       98        15    118  59.0
9   10       3    50       98        45    148  74.0
10  11       3    65       65        65    130  65.0
11  12       3    45       85        32    130  65.0
12  13       4    46       98        65    144  72.0
13  14       4    48       87        12    135  67.5
14  15       4    75       56        78    131  65.5
15  16       4    58       98        65    156  78.0
16  17       5    65       68        98    133  66.5
17  18       5    80       78        90    158  79.0
18  19       5    89       68        87    157  78.5
19  20       5    78       83        58    161  80.5

In [52]:
exam.assign(test = np.where(exam["science"] >= 60, "pass", "fail"))

    id  nclass  math  english   science  test
0    1       1    50       98  10000000  pass
1    2       1    60       97        60  pass
2    3       1    45       86        78  pass
3    4       1    30       98        58  fail
4    5       2    25       80        65  pass
5    6       2    50       89        98  pass
6    7       2    80       90        45  fail
7    8       2    90       78        25  fail
8    9       3    20       98        15  fail
9   10       3    50       98        45  fail
10  11       3    65       65        65  pass
11  12       3    45       85        32  fail
12  13       4    46       98        65  pass
13  14       4    48       87        12  fail
14  15       4    75       56        78  pass
15  16       4    58       98        65  pass
16  17       5    65       68        98  pass
17  18       5    80       78        90  pass
18  19       5    89       68        87  pass
19  20       5    78       83        58  fail

In [54]:
exam.assign(total = exam["math"] + exam["english"]).sort_values("total", ascending=False)

    id  nclass  math  english   science  total
6    7       2    80       90        45    170
7    8       2    90       78        25    168
19  20       5    78       83        58    161
17  18       5    80       78        90    158
18  19       5    89       68        87    157
1    2       1    60       97        60    157
15  16       4    58       98        65    156
0    1       1    50       98  10000000    148
9   10       3    50       98        45    148
12  13       4    46       98        65    144
5    6       2    50       89        98    139
13  14       4    48       87        12    135
16  17       5    65       68        98    133
2    3       1    45       86        78    131
14  15       4    75       56        78    131
10  11       3    65       65        65    130
11  12       3    45       85        32    130
3    4       1    30       98        58    128
8    9       3    20       98        15    118
4    5       2    25       80        65    105

In [55]:
exam.assign(new = lambda x: x["math"] + x["english"] + x["science"])

    id  nclass  math  english   science       new
0    1       1    50       98  10000000  10000148
1    2       1    60       97        60       217
2    3       1    45       86        78       209
3    4       1    30       98        58       186
4    5       2    25       80        65       170
5    6       2    50       89        98       237
6    7       2    80       90        45       215
7    8       2    90       78        25       193
8    9       3    20       98        15       133
9   10       3    50       98        45       193
10  11       3    65       65        65       195
11  12       3    45       85        32       162
12  13       4    46       98        65       209
13  14       4    48       87        12       147
14  15       4    75       56        78       209
15  16       4    58       98        65       221
16  17       5    65       68        98       231
17  18       5    80       78        90       248
18  19       5    89       68        87       244
19  20       5    78       83        58       219

In [56]:
exam.assign(total = exam["math"], mean = lambda x: x["total"]/3)
#여기서 람다 안쓰면 에러 뜸

    id  nclass  math  english   science  total       mean
0    1       1    50       98  10000000     50  16.666667
1    2       1    60       97        60     60  20.000000
2    3       1    45       86        78     45  15.000000
3    4       1    30       98        58     30  10.000000
4    5       2    25       80        65     25   8.333333
5    6       2    50       89        98     50  16.666667
6    7       2    80       90        45     80  26.666667
7    8       2    90       78        25     90  30.000000
8    9       3    20       98        15     20   6.666667
9   10       3    50       98        45     50  16.666667
10  11       3    65       65        65     65  21.666667
11  12       3    45       85        32     45  15.000000
12  13       4    46       98        65     46  15.333333
13  14       4    48       87        12     48  16.000000
14  15       4    75       56        78     75  25.000000
15  16       4    58       98        65     58  19.333333
16  17       5    65       68        98     65  21.666667
17  18       5    80       78        90     80  26.666667
18  19       5    89       68        87     89  29.666667
19  20       5    78       83        58     78  26.000000

In [58]:
mpg_new = mpg.copy()
mpg_new.assign(total = mpg_new["cty"] + mpg_new["hwy"],
              mean = lambda x: x["total"] / 2, )

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category,total,mean
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,47,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,50,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,51,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,51,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,42,21.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize,47,23.5
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize,50,25.0
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize,42,21.0
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize,44,22.0
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize,43,21.5